### ISSUE TITLE
Local plugin builds typo in README

### ISSUE THREAD

**Issue by caleteeter** [ConsenSys/quorum-security-plugin-enterprise#5]
The [README](https://github.com/ConsenSys/quorum-security-plugin-enterprise/blob/master/README.md) here states that to build plugins locally, an environment variable named PLUGIN_DIST_PATH, however the [Makefile](https://github.com/ConsenSys/quorum-security-plugin-enterprise/blob/master/Makefile) is using PLUGIN_DEST_PATH.

Also, the [README](https://github.com/ConsenSys/quorum-security-plugin-enterprise/blob/master/README.md) says to run
`PLUGIN_DIST_PATH=<path to store plugin distribution zip file> make dist` however the dist recipe does nothing with the plugin path, dist-local does.

**Comment by caleteeter** [comment]
Adding PR #6 for fix.

**Comment by trung** [comment]
PR merged. Thanks
